#                    ---===< 注意 >===---
#
# 1. LobiAPIは規約違反です。使用するなら自己責任でお願いします。
# 2. このプラグインを使って起きた事に対してInkoHXは責任を負いません。

email: ""
password: ""

# 宣伝文
message: "114514"
invite: "https://lobi.co/invite/eJmGW36v15pE7u9LsoWvaFDKxKH"